src/Entity/UserInfo.php
<?php

namespace App\Entity;

use App\Repository\UserInfoRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=UserInfoRepository::class)
 */
class UserInfo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;
 
    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="text")
     */
    private $images;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getImages()
    {
        return $this->images;
    }

    public function setImages($images)
    {
        $this->images = json_encode($images);

        return $this;
    }

    public function addImage($image)    
    {
        $this->images[] = $image;

        return $this;
    }
}

src/Form/UserInfoType.php
<?php

namespace App\Form;

use App\Entity\UserInfo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserInfoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('description')
            ->add('images', FileType::class, [
                'multiple' => true,
                'attr'     => [
                    'accept' => 'image/*',
                    'multiple' => 'multiple'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => UserInfo::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\UserInfo;
use App\Form\UserInfoType;
use App\Message\PdfGenerator;
use App\Repository\UserInfoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Messenger\Stamp\DelayStamp;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;

use Dompdf\Dompdf;
/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="app_user_index", methods={"GET"})
     */
    public function index(UserInfoRepository $userInfoRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'user_infos' => $userInfoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_user_new", methods={"GET", "POST"})
     */
    public function new(Request $request, UserInfoRepository $userInfoRepository, MessageBusInterface $bus): Response
    {
        $userInfo = new UserInfo();
        $form = $this->createForm(UserInfoType::class, $userInfo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            $fileNames = $this->upload_images($form);

            $userInfo->setImages($fileNames);
            $userInfoRepository->add($userInfo, true);

            //this will dispatch the transport for generating pdf
            $bus->dispatch(new PdfGenerator($userInfo->getId()));
            
            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user_info' => $userInfo,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_user_show", methods={"GET"})
     */
    public function show(UserInfo $userInfo): Response
    {
        return $this->render('user/show.html.twig', [
            'user_info' => $userInfo,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_user_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, UserInfo $userInfo, UserInfoRepository $userInfoRepository): Response
    {
        $form = $this->createForm(UserInfoType::class, $userInfo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userInfoRepository->add($userInfo, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user_info' => $userInfo,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_user_delete", methods={"POST"})
     */
    public function delete(Request $request, UserInfo $userInfo, UserInfoRepository $userInfoRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$userInfo->getId(), $request->request->get('_token'))) {
            $userInfoRepository->remove($userInfo, true);
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }

    private function upload_images($form) 
    {
        /** @var UploadedFile $imageFile */
        $imageFile = $form->get('images')->getData();
        $fileNames = array();
        if ($imageFile) {
            foreach ($imageFile as $imgFile) {
                $originalFilename = pathinfo($imgFile->getClientOriginalName(), PATHINFO_FILENAME);

                $safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$imgFile->guessExtension();

                // Move the file to the directory
                try {
                    $imgFile->move(
                        $this->getParameter('images_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    echo 'Impossible d\'enregistrer l\'image';
                }
                
                array_push($fileNames, $newFilename);
                
            }
        }

        return $fileNames;
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        {% endblock %}
 
        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user_info.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user_info.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    <div class="form-group">
        {{ form_row(form.name, {'attr': {'class': 'form-control'}}) }}
    </div>
    <div class="form-group">
        {{ form_row(form.description, {'attr': {'class': 'form-control'}}) }}
    </div>
      <div class="form-group">
        {{ form_row(form.images, {'attr': {'class': 'form-control'}}) }}
    </div>
    <button class="btn {{ button_color|default('btn-outline-primary') }}  mt-3">{{ button_label|default('Save Project') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}
 
{% block title %}Edit Project{% endblock %}
 
{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Edit Project</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-info float-right" href="{{ path('app_user_index') }}"> 
                    View All Projects
                </a>
            </div>
            <div class="card-body">
                {% include 'user/_form.html.twig' with {'button_label': 'Update Project', 'button_color': 'btn-outline-success'}  %}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}
 
{% block title %}User index{% endblock %}
 
{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">User Manager</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-primary" href="{{ path('app_user_new') }}"> 
                    Create New User 
                </a>
            </div>
            <div class="card-body">
                <table class="table table-bordered">
                    <tr>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Date Created</th>
                        <th>Date Updated</th>
                        <th width="240px">Action</th>
                    </tr>
                    {% for user_info in user_infos %}
                    <tr>
                        <td>{{ user_info.name }}</td>
                        <td>{{ user_info.description }}</td>
                        <td>{{ user_info.createdAt ? user_info.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                        <td>{{ user_info.updatedAt ? user_info.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                        <td>
                            <form method="post" action="{{ path('app_user_delete', {'id': user_info.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                <a
                                    class="btn btn-outline-info"
                                    href="{{ path('app_user_show', {'id': user_info.id}) }}">
                                    Show
                                </a>
                                <a
                                    class="btn btn-outline-success"
                                    href="{{ path('app_user_edit', {'id': user_info.id}) }}">
                                    Edit
                                </a>
 
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user_info.id) }}">
                                <button class="btn btn-outline-danger">Delete</button>
                            </form>
                        </td>
                        <td> <a href="/pdf/user_{{ user_info.id }}.pdf" target="_blank">Download Generated PDF</a> </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
 
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}
 
{% block title %}New User{% endblock %}
 
{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Create User</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-info float-right" href="{{ path('app_user_index') }}"> 
                    View All Users
                </a>
            </div>
            <div class="card-body">
                 {{ include('user/_form.html.twig') }}
            </div>
        </div>
    </div>
{% endblock %}

templates/user/pdf.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Generated PDF</title>
</head>
<body>
    <div style="margin: 0 auto;display: block;width: 500px;">
        <table width="100%" border="1">
    
            <tr>
                <td>Name:</td>
                <td>{{name}}</td>
            </tr>
            <tr>
                <td>Description:</td>
                <td>{{description}}</td>
            </tr>
            <tr>
                <td>Images:</td>
                <td>
                <ul>
                    {% for imgSrc in images %}
                        <li>
                       
                            <img src = "{{ imgSrc }}" style="width:200px;"/>
                        </li>
                    {% endfor %}
                </ul>
               
                
                </td>
            </tr>
        </table>
    </div>
</body>
</html>

templates/user/show.html.twig
{% extends 'base.html.twig' %}
 
{% block title %}User{% endblock %}
 
{% block body %}
    <div class="container">
        <h2 class="text-center mt-5 mb-3">Show User</h2>
        <div class="card">
            <div class="card-header">
                <a class="btn btn-outline-info float-right" href="{{ path('app_user_index') }}"> 
                    View All Users
                </a>
            </div>
            <div class="card-body">
                <b class="text-muted">Name:</b>
                <p>{{ user_info.name }}</p>
                <b class="text-muted">Description:</b>
                <p>{{ user_info.description }}</p>
                <b class="text-muted">Date Created:</b>
                <p>{{ user_info.createdAt ? user_info.createdAt|date('Y-m-d H:i:s') : '' }}</p>
                <b class="text-muted">Date Updated:</b>
                <p>{{ user_info.updatedAt ? user_info.updatedAt|date('Y-m-d H:i:s') : '' }}</p>
            </div>
        </div>
    </div>
{% endblock %}